[package]
name = "bevy_curve_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11" }
bevy-inspector-egui = "0.19.0"
pretty-type-name = "1.0"
